---
title: "Testprotocol"
---

Elk ontwikkeld script wordt getest. Dit testprotocol bestaat uit unittesten en integratietesten.
Met unittesten testen we of de individuele componenten van de broncode goed werken (bijv. als de gebruiker foutieve data opgeeft).
Bij het maken van unittesten is het doel om een totale dekking van 80% te halen over de gehele code, dit kan gecontroleerd worden met `pytest -cov`.
Bij sommige modules is dit het makkelijk om alle code te vatten in een test, in die gevallen is dit dan ook de bedoeling om dit te doen.
Doordat de interactie met een PostgreSQL database of FEWS REST-API niet makkelijk te verwerken is in een automatische test, is er per functie geen strikte eis.
Om toch de interactie met componenten die beveiligd zijn en om de samenwerking tussen de verschillende scripts te controleren, worden integratietesten uitgevoerd.
In de ontwikkelfase vinden deze integratietesten plaats aan het einde van de sprints door een deel van de project groep die niet de code actief heeft ontwikkeld.
In de beheerfase zal het team dat de code blijft beheren deze integratietesten blijven uitvoeren.
