# Installatie-instructies

De Toolbox Continu Inzicht kan op verschillende manieren worden gebruikt:

1. Als vervanging van de huidige Continu Inzicht back-end
1. Als losstaande modules
1. Als ontwikkelaar

## Vervanging

Om de toolbox als vervanging van de huidige Continu Inzicht back-end te gebruiken, zal in de toekomst meer informatie beschikbaar gesteld worden.
De oude back-end kan met weinig aanpassingen worden vervangen door de nieuwe code. Verdere aanpassingen die in de toolbox worden gedaan, kunnen dan worden meegenomen.

## Losstaande modules

Om de toolbox als losstaande modules te gebruiken kan je de code downloaden van [PyPi](https://pypi.org/project/toolbox-continu-inzicht/).

```python
pip install toolbox-continu-inzicht[all]
```

Vanwege het aantal afhankelijkheden is het aan te raden om een nieuwe conda environment te gebruiken. Hiervoor kan gebruik gemaakt worden van de `requirements.yaml` in de source map op GitHub. Met het volgende conda commando kan deze worden geïnstalleerd.

```bash
conda env create --file=https://raw.githubusercontent.com/continu-inzicht/toolbox-continu-inzicht/refs/heads/main/src/requirements.yaml
```

### Alleen delen van de toolbox gebruiken

Verschillende modules hebben ook verschillende afhankelijkheden, voor geavanceerde gebuikers kan het fijn zijn om niet alle afhankelijkeheden te instaleren.
Om deze reden kunnen de verschillende modules ook los worden geinstalleerd:

- `pip install toolbox_continu_inzicht[fragility_curves]`
- `pip install toolbox_continu_inzicht[loads]`
- `pip install toolbox_continu_inzicht[inspections]`
- `pip install toolbox_continu_inzicht[sections]`
- `pip install toolbox_continu_inzicht[io]`
- `pip install toolbox_continu_inzicht[flood_scenarios]`

Het commando `pip install toolbox-continu-inzicht[all]` doet voert alle bovenstaande commandos uit.

Om te testen of dit goed werkt staat een test plan beschreven in de repo [test-package-installation](https://github.com/continu-inzicht/test-package-installation).

## Als ontwikkelaar

We maken gebruik van [pixi](https://pixi.sh/latest/) om de conda environment te beheren en delen, dit kent een wat steilere leer curve en wordt daarom vooral aan ontwikkelaar aangeboden.

##### windows

```powershell
iwr -useb https://pixi.sh/install.ps1 | iex
```

##### Linux

```bash
curl -fsSL https://pixi.sh/install.sh | bash
```

#### Installeer python packages met pixi

Met het `Pixi` commando in powershell kun je vervolgens de juiste python bestanden installeren:

```bash
 cd ..\toolbox-continu-inzicht
 pixi install
```

Dit kan even duren, Pixi gebruikt het `pixi.lock` bestand om de juiste packages te laden en zet deze in de `.pixi` map.

#### JupyterLab

```bash
pixi run jupyter lab
```

Of selecteer de juiste Python-instantie: `..\.pixi\envs\default\python.exe` in je ontwikkelomgeving.
In VS Code kan dit met `Ctrl + shift + p` dan `Python: Select Interpreter`.

Zie de ['Richtlijnen voor bijdragen aan Toolbox Continu Inzicht'](https://continu-inzicht.github.io/toolbox-continu-inzicht/contributing.html) voor meer informatie.
