---
title: "Modules"
---

De Toolbox Continu Inzicht is in sprints ontwikkeld waarbij één of meerdere modules is ontwikkeld.
Voor elke module worden Python-scripts ontwikkeld waarmee een functie kan worden uitgevoerd.
Deze modules kunnen los gebruikt worden of vormen samen een geheel.
Naast de functies is per module een beschrijving beschikbaar en zijn er voorbeelden hoe de code gebruikt kan worden met uitleg.

1.  [Basis architectuur Toolbox Continu Inzicht](modules/architectuur.qmd)

    In de toolbox continu inzicht is een belangrijk uitgangspunt dat verschillende data formaten gebruikt kunnen worden, de functie zijn zo opgezet dat elk formaat als in of uitvoer kan dienen.

2.  [Belastingen inlezen en classificeren](modules/belastingen.qmd)

    Om inzicht te krijgen in de veiligheid van waterkeringen is het van belang om de belastingen op de waterkeringen in kaart te brengen.
    Dit kunnen waterstanden op het buitenwater (zee, rivieren of meren) zijn, maar ook grondwaterstanden. Er zijn verschillende functies geïmplementeerd voor het inlezen, opslaan en classificeren van historische en voorspelde belastingen.

3.  [Bepalen fragility curves](modules/bepalen_fragility_curves.qmd)

    Fragility curves kunnen voor verschillende faalmechanismes worden opgesteld. In de toolbox wordt voor GEKB (overloop en golfoverslag van dijken) en STPH (piping en heave bij dijken) een functionaliteit aangeboden voor het afleiden van fragility curves. Daarnaast is het mogelijk om voor andere faalmechanismen een door de gebruiker vooraf opgestelde fragility curve te importeren.


4.  [Bijstellen fragility curves](modules/bijstellen_fragility_curves.qmd)

    In sommige gevallen is het gewenst om een fragility curve aan te passen vanwege nieuwe inzichten, bijv. vanuit beheer, na grondonderzoek of dijkverbetering. Denk hierbij aan aanpassen van het dijkprofiel of de sterkte van de ondergrond of de bekleding. Het is mogelijk om een nieuwe fragility curve te berekenen of de conditionele faalkansen aan te passen.

5.  [Conditionele kansen en status waterkering per sectie](modules/kansen_en_status_per_sectie.qmd)

    Per dijkvak (sectie) wordt een statusbeeld bepaald op basis van de actuele of voorspelde belasting en de fragility curve. Dit statusbeeld is voor elk dijkvak te bepalen voor elk individueel faalmechanisme of een totaalbeeld o.b.v. alle faalmechanismen. 

6.  [Impactanalyse: effect nieuwe statistiek en rekenregels op de faalkans](modules/impactanalyse.qmd)

    Een fragility curve beschrijft de conditionele kans gegeven een belasting, zoals een waterstand. Om inzicht te krijgen in de faalkans per jaar moet de fragility curve gecombineerd worden met de kans van voorkomen van verschillende waterstanden (overschrijdingsfrequentielijn waterstanden). Hiermee is het mogelijk om het effect van veranderingen in de statistiek van de belasting, bijvoorbeeld door klimaatverandering, een systeemmaatregel zoals rivierverruiming of nieuwe rekenregels, op de faalkans per jaar te vergelijken met een referentiesituatie. De duiding van de verandering van de faalkans is in klassen van grote kansafname tot grote kanstoename. Deze klassen zijn door de gebruiker zelf te definieren. 

7.  [Inspectieresultaten inlezen en weergeven](modules/inspectieresultaten.qmd)

    Het statusbeeld van de dijken op basis van fragility curves, eventueel bijgesteld met een beheerdersoordeel, is te verrijken met informatie uit de inspecties. Dit kunnen historische waarnemingen zijn, maar ook de voorjaarsinspectie of een melding tijdens een calamiteiteninspectie. Met de Toolbox Continu Inzicht is het mogelijk om de inspectiedata te filteren, classificeren en kaart te tonen in de viewer van de Toolbox Continu Inzicht.
