---
title: "Voorbeelden"
---


Op deze pagina staan notebooks met voorbeelden van het gebruik van de toolbox.

De notebooks met bijbehorende data en configuratie zijn beschikbaar op [GitHub](https://github.com/continu-inzicht/toolbox-continu-inzicht/tree/main/docs/examples/notebooks).

Tijdens het ontwikkelen zijn ook `development` notebooks gemaakt. Op termijn zullen de meeste ook naar deze wiki pagina worden gemigreerd. De notebooks gemaakt voor de demo hebben vaak interactie met de database om zo de viewer te laten zien. Deze zullen hier niet beschikbaar worden gesteld, wel zijn ze te vinden onder [`tests` op GitHub](https://github.com/continu-inzicht/toolbox-continu-inzicht/tree/main/tests/examples).


De van de verschillende modules zijn voorbeelden gemaakt:

- [Architectuur voorbeeld](examples/notebooks/1.proof_of_concept.ipynb)
- [Inladen van belastingen](examples/notebooks/2.belastingen_inladen.ipynb)
- [Fragility curve overtopping met bodemhoogte/strijklengte](examples/notebooks/3.fragility_curve_overtopping_bedlevelfetch.ipynb)
- [Aanpassen van geïntegreerde faalkans](examples/notebooks/4.adjust_integrated_statistics.ipynb)
- [Inspectieresultaten](examples/notebooks/5.inspectieresultaten.ipynb)
- [Maatregelen](examples/notebooks/6.fragility_curve_from_cache.ipynb)
- [Overstromingsrisico](examples/notebooks/7.rekentest_flood_scenarios.ipynb)
- [Fragility curve overtopping met golfdata](examples/notebooks/8.fragility_curve_overtopping_wavedata.ipynb)

De modules lopen echter maar 1 module langs, in werkelijkheid worden de verschillende modules gecombineerd.

- ['Quick start guide'](examples/notebooks/102.quick_start_guide.ipynb)
- [Alle modules op een rij](examples/notebooks/103.all_modules.ipynb)

Daarnaast zijn er ook notebooks met meer technische uitleg over aspecten van de toolbox:

- [Gebruik van logging](examples/notebooks/100.logging.ipynb)
- [WMS laag instellen in de viewer](examples/notebooks/101.WMS_laag_naar_database.ipynb)
