# base.config { #toolbox_continu_inzicht.base.config }

`base.config`



## Classes

| Name | Description |
| --- | --- |
| [Config](#toolbox_continu_inzicht.base.config.Config) | Basis functie om de configuratie in te laden. |

### Config { #toolbox_continu_inzicht.base.config.Config }

`base.config.Config()`

Basis functie om de configuratie in te laden.

#### Parameters

| Name          | Type   | Description                                                                                      | Default    |
|---------------|--------|--------------------------------------------------------------------------------------------------|------------|
| `config_path` |        | Pad naar een  `.yaml` bestand waarin per functie staat beschreven wat de in/ouput bestanden zijn | _required_ |

#### Attributes

| Name | Description |
| --- | --- |
| [WaardesDelenTwee](#toolbox_continu_inzicht.base.config.Config.WaardesDelenTwee) |  |
| [WaardesKeerTwee](#toolbox_continu_inzicht.base.config.Config.WaardesKeerTwee) |  |
| [config_path](#toolbox_continu_inzicht.base.config.Config.config_path) |  |
| [dump](#toolbox_continu_inzicht.base.config.Config.dump) |  |
| [global_variables](#toolbox_continu_inzicht.base.config.Config.global_variables) |  |
| [toegelaten_functies](#toolbox_continu_inzicht.base.config.Config.toegelaten_functies) |  |

#### Methods

| Name | Description |
| --- | --- |
| [lees_config](#toolbox_continu_inzicht.base.config.Config.lees_config) | Laad het gegeven pad in, zet de configuraties klaar in de Config class |

##### lees_config { #toolbox_continu_inzicht.base.config.Config.lees_config }

`base.config.Config.lees_config()`

Laad het gegeven pad in, zet de configuraties klaar in de Config class