# proof_of_concept.voorbeeld_module { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module }

`proof_of_concept.voorbeeld_module`



## Classes

| Name | Description |
| --- | --- |
| [WaardesDelenTwee](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee) | Voorbeeld class die laat zien hoe de arcitectuur werkt |
| [WaardesKeerTwee](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee) | Voorbeeld class die laat zien hoe de arcitectuur werkt |

### WaardesDelenTwee { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee }

`proof_of_concept.voorbeeld_module.WaardesDelenTwee()`

Voorbeeld class die laat zien hoe de arcitectuur werkt

#### Attributes

| Name | Description |
| --- | --- |
| [data_adapter](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.data_adapter) |  |
| [df_in](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.df_in) |  |
| [df_out](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.df_out) |  |
| [input](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.input) |  |
| [output](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.output) |  |

#### Methods

| Name | Description |
| --- | --- |
| [delen_door_twee](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.delen_door_twee) | Vermenigvuldigd de meetstation waardes met 2 als voorbeeld |
| [run](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.run) | Runt de funcies en stuur de df terug |

##### delen_door_twee { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.delen_door_twee }

`proof_of_concept.voorbeeld_module.WaardesDelenTwee.delen_door_twee(dataframe)`

Vermenigvuldigd de meetstation waardes met 2 als voorbeeld

##### run { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesDelenTwee.run }

`proof_of_concept.voorbeeld_module.WaardesDelenTwee.run(input=None, output=None)`

Runt de funcies en stuur de df terug

### WaardesKeerTwee { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee }

`proof_of_concept.voorbeeld_module.WaardesKeerTwee()`

Voorbeeld class die laat zien hoe de arcitectuur werkt

Args:
    data_adapter: DataAdapter
                 Leest

#### Attributes

| Name | Description |
| --- | --- |
| [data_adapter](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.data_adapter) |  |
| [df_in](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.df_in) |  |
| [df_out](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.df_out) |  |
| [input](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.input) |  |
| [output](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.output) |  |

#### Methods

| Name | Description |
| --- | --- |
| [keer_twee](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.keer_twee) | Deelt de meetstation waardes door 2 als voorbeeld |
| [run](#toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.run) | Runt de funcies en stuur de df terug |

##### keer_twee { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.keer_twee }

`proof_of_concept.voorbeeld_module.WaardesKeerTwee.keer_twee(dataframe)`

Deelt de meetstation waardes door 2 als voorbeeld

##### run { #toolbox_continu_inzicht.proof_of_concept.voorbeeld_module.WaardesKeerTwee.run }

`proof_of_concept.voorbeeld_module.WaardesKeerTwee.run(input=None, output=None)`

Runt de funcies en stuur de df terug