---
title: "Impactanalyse: effect nieuwe statistiek en rekenregels op de faalkans"
---

De module impactanalyse is conceptueel anders dan de functionaliteit in de modules real-time en what-if. De gebruiker kan het effect van veranderingen in de statistiek van de belasting of rekenregels in kaart brengen. 
Hiervoor is in de Toolbox Continu Inzicht een functionaliteit toegevoegd om per dijkvak (sectie) de faalkans per jaar te berekenen. De faalkans per jaar wordt per dijvak berekend door het integreren van overschrijdingsfrequentielijn van een belasting (overschrijdingskans per jaar van belastingen) met een fragility curve (faalkans gegeven een belasting).

### Jaarlijkse faalkans
Voor het berekenen van de ge誰ntegreerde faalkans zijn twee opties: (1) per dijkvak per faalmechanisme met de functie `IntegrateFragilityCurve`; of (2) voor meerdere dijkvakken en faalmechanismes met de functie `IntegrateFragilityCurveMultiple`. Qua configuratie is de functie `IntegrateFragilityCurveMultiple` identiek aan de functie `IntegrateFragilityCurve`, alleen loopt de functie `IntegrateFragilityCurveMultiple` nog extra de kolommen `section_id` en `mechanism_id` langs om voor alle fragility curves de ge誰ntegreerde kans te berekenen.

::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"
    moments: [-24,0,24,48]

    IntegrateFragilityCurve:
        refine_step_size: 0.05

DataAdapter:
    default_options:
        csv:
            sep: ","
    fragility_curve_csv:
        type: csv
        file: "single_fragility_curve.csv"
    exceedance_curve_csv:
        type: csv
        file: "single_exceedance_curve.csv"
    result:
        type: csv
        file: "result.csv"
```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.fragility_curves import IntegrateFragilityCurve

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)
integrate_statistics_per_section = IntegrateFragilityCurve(data_adapter=data_adapter)
integrate_statistics_per_section.run(
    input=["exceedance_curve_csv", "fragility_curve_multi_csv"], output="result"
)

```
:::


### Reliability Update (methode bewezen sterkte)

Naast het berekenen van de faalkans per jaar per dijkvak, is het mogelijk om het effect van bewezen sterkte mee te nemen in de faalkansberekening. 
Met gebruik van `FragilityCurve.reliability_update` kan de fragility curve worden aangepast door een overleefde belastingsituatie in rekening te brengen. Ook hier geldt dat dit een waterstand, grondwaterstand of elke andere belastingparameter kan zijn. 
Hierdoor kan ook weer een ge誰ntegreerde faalkans per jaar worden berekend met een nieuwe fragility curve, waarbij het effect van een overleefde belastingsituatie in is meegenomen.
Dit stappenplan wordt weergegeven in het voorbeeld-notebook [Aanpassen van ge誰ntegreerde fragility curves
](../examples/notebooks/4.adjust_integrated_statistics.ipynb).
