---
title: "Maatregelen"
---

Tijdens crisis situaties kunnen maatregelen worden getroffen, om in dat soort situaties ook de actuele kansen inzichtelijk te maken kunnen de fragility curves worden aangepast. Voor alle fragility curve kunnen worden verschoven. Voor GEKB curves die in de toolbox 'on the fly' worden berekend kan de kruinhoogte worden aangepast, zie de module [bijstellen](./bijstellen_fragility_curves.qmd) voor meer informatie.
Als de fragility curves van de voren zijn berekend met een bepaalde maatregel, kunnen we de huidige curve vervangen met een voorberekende curve die past bij de maatregel.
Hiervoor zijn 4 verschillende functies uitgewerkt, afhankelijk van de implementatie kan gekozen worden voor een van de vier.

1. De fragility curve kan per dijk vak aangepast worden voor één mechanisme met [`LoadCachedFragilityCurveOneFailureMechanism`](#sec-LoadCachedFragilityCurveOneFailureMechanism). Hierbij is de aanpassing het meest overzichtelijk, maar het is wel omslachtig als er veel dijkvakken zijn.

1. Voor een dijkvak, maar voor alle faalmechanismen in een keer de fragility curves aanpassen met `LoadCachedFragilityCurve`.

1. Voor alle dijkvakken en faalmechanismes in één keer alle fragility curves aanpassen met `LoadCachedFragilityCurveMultiple`.

1. Zelf logica in python implementeren om de bijbehorende fragility curve aan te passen door de `FragilityCurve` class te gebruiken.


### Per vak & per faalmechanisme de fragility curve aanpassen{#sec-LoadCachedFragilityCurveOneFailureMechanism}

Om voor één vak de fragility curve van één faalmechanisme aan te passen kan de functie `LoadCachedFragilityCurveOneFailureMechanism` worden gebruikt. Hier moet naast de standaard kolomen voor een fragility curve (`hydraulicload` & `failure_probability`) ook een id worden opgegeven dat aangeeft bij welke maatregel een fragility curve hoort: `measure_id`. In het input bestand staan meerdere curves met maatregelen, standaard heeft de fragilitycurve zonder maatregel een id `0`. Deze standaard waarde kan worden aandepast met `default_measure_id` in de `yaml`. Omdat de 3 functies `LoadCachedFragilityCurve*` die hier worden beschreven functionaliteit delen moet dit altijd onder he kopje van `LoadCachedFragilityCurve`.

::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"
    LoadCachedFragilityCurve:
        default_measure_id: 0

DataAdapter:
    fragility_curve_one_section_one_failure:
        type: csv
        file: "fragility_curve_one_section_one_failure.csv"
    resulting_fragility_curve:
        type: csv
        file: "hidden_resulting_fragility_one_section_one_failure.csv"

```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.fragility_curves import LoadCachedFragilityCurveOneFailureMechanism

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)
load_cached_fragility_curve = LoadCachedFragilityCurveOneFailureMechanism(
    data_adapter=data_adapter
)
load_cached_fragility_curve.run(
    input="fragility_curve_one_section_one_failure",
    output="resulting_fragility_curve",
    measure_id=1,
)
```
:::

### Per vak voor alle faalmechanisme de fragility curve aanpassen{#sec-LoadCachedFragilityCurve}

#### Per faalmechanisme dezelfde maatregel{#sec-LoadCachedFragilityCurve-alle-vakken}
Om voor één vak de fragility curve van alle faalmechanisme aan te passen kan de functie `LoadCachedFragilityCurve` worden gebruikt. Hier moet naast [`measure_id`](#sec-LoadCachedFragilityCurveOneFailureMechanism), het id van de faalmechanisme worden opgegeven: `failuremechanism_id`. Per faalmechanisme wordt dan de fragility curve aangepast naar de fragility curve met het bijbehorende maatregel. Op deze manier worden dan alle faalmechanisme aangepast naar de gegeven maatregel. Als de maatregel per faalmechanisme anders is moet ook deze koppeling in een tabel worden mee gegeven, zie hiervoor het volgende kopje: [andere maatregel per faalmechanisme](#sec-LoadCachedFragilityCurve-per-vak).

::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"
    LoadCachedFragilityCurve:
        default_measure_id: 0

DataAdapter:
    fragility_curve_one_section_multi_failure:
        type: csv
        file: "fragility_curve_one_section_multi_failure.csv"
    resulting_fragility_curve:
        type: csv
        file: "hidden_resulting_fragility_one_section_multi_failure.csv"

```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.fragility_curves import LoadCachedFragilityCurve

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)

load_cached_fragility_curve = LoadCachedFragilityCurve(data_adapter=data_adapter)
load_cached_fragility_curve.run(
    input="fragility_curve_one_section_multi_failure",
    output="resulting_fragility_curve",
    measure_id=1,
)
```
:::
#### Andere maatregel per faalmechanisme{#sec-LoadCachedFragilityCurve-per-vak}

Als een andere maatregel wordt toegepast per faalmechanisme moet een koppeling worden gemaakt tussen de faalmechanisme en de maatregel. Hiervoor moeten een tabel met `failuremechanism_id` en `measure_id` worden meegegeven. It dat geval is de variable `measure_id` standaard `None`.
::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"
    LoadCachedFragilityCurve:
        default_measure_id: 0

DataAdapter:
    fragility_curve_one_section_multi_failure:
        type: csv
        file: "fragility_curve_one_section_multi_failure.csv"
    failuremechanism_id_to_measure_id:
        type: csv
        file: "failuremechanism_id_to_measure_id.csv"
    resulting_fragility_curve:
        type: csv
        file: "hidden_resulting_fragility_one_section_multi_failure.csv"

```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.fragility_curves import LoadCachedFragilityCurve

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)

load_cached_fragility_curve = LoadCachedFragilityCurve(data_adapter=data_adapter)
load_cached_fragility_curve.run(
    input=[
        "fragility_curve_one_section_multi_failure",
        "failuremechanism_id_to_measure_id",
    ],
    output="resulting_fragility_curve"
)
```
:::

### Voor alle vakken en alle faalmechanisme de {#sec-LoadCachedFragilityCurveMultiple}

Om voor alle vak de fragility curve van alle faalmechanisme aan te passen kan de functie `LoadCachedFragilityCurveMultiple` worden gebruikt. Hier moet naast [`measure_id`](#sec-LoadCachedFragilityCurveOneFailureMechanism) en [`failuremechanism_id`](#sec-LoadCachedFragilityCurve) ook de `section_id` worden opgegeven. Per dijkvak (section) wordt dan de fragility curve aangepast naar de fragility curve met het bijbehorende maatregel. Op deze manier worden dan alle vakken aangepast naar de gegeven maatregel. Als de maatregel per faalmechanisme of vak anders is moet ook deze koppeling in een tabel worden mee gegeven, zie hiervoor het volgende kopje: [Andere maatregel per vak & faalmechanisme](#sec-LoadCachedFragilityCurve-per-vak).


#### Per vak & faalmechanisme dezelfde maatregel{#sec-LoadCachedFragilityCurveMultiple-alle-vakken}

In het geval dat alle vakken en fragility curves dezelfde maatregel hebben kan deze direct worden opgegeven via de variable `measure_id`.

::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"
    LoadCachedFragilityCurve:
        default_measure_id: 0

DataAdapter:
    fragility_curve_multi_section_multi_failure:
        type: csv
        file: "fragility_curve_multi_section_multi_failure.csv"
    resulting_fragility_curve:
        type: csv
        file: "hidden_resulting_fragility_one_section_multi_failure.csv"

```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.fragility_curves import LoadCachedFragilityCurveMultiple

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)
load_cached_fragility_curve = LoadCachedFragilityCurveMultiple(
    data_adapter=data_adapter
)
load_cached_fragility_curve.run(
    input="fragility_curve_one_section_one_failure",
    output="resulting_fragility_curve",
    measure_id=1,
)
```
:::

#### Andere maatregel per vak & faalmechanisme{#sec-LoadCachedFragilityCurve-per-vak}

Om een koppeling te maken van vak en faalmechanisme naar maatregel is een extra tabel nodig. Hiervoor moeten een tabel met `section_id`,`failuremechanism_id` en `measure_id` worden meegegeven.
It dat geval is de variable `measure_id` standaard `None`.

::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"
    LoadCachedFragilityCurve:
        default_measure_id: 0

DataAdapter:
    fragility_curve_multi_section_multi_failure:
        type: csv
        file: "fragility_curve_multi_section_multi_failure.csv"
    section_id_to_measure_id:
        type: csv
        file: "section_id_to_measure_id.csv"
    resulting_fragility_curve:
        type: csv
        file: "hidden_resulting_fragility_one_section_multi_failure.csv"

```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.fragility_curves import LoadCachedFragilityCurveMultiple

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)
load_cached_fragility_curve = LoadCachedFragilityCurveMultiple(
    data_adapter=data_adapter
)
load_cached_fragility_curve.run(
    input=["fragility_curve_one_section_one_failure","section_id_to_measure_id"],
    output="resulting_fragility_curve"
)
```
:::


### FragilityCurve{#sec-FragilityCurve}

Als laatste kan ook gekozen worden voor een eigen implementatie. Dit kan handig zijn als de keuze van de `measure_id` af hangt van een fysiesche waarde: bijv. de windrichting. Hiervoor gebruik je de class `FragilityCurve`. _Let op: deze functionaliteit is voor de geavanceerde gebruiker_.

::: {.panel-tabset}
## Configuratie
```yaml
GlobalVariables:
    rootdir: "data_sets"

DataAdapter:
    fragility_curve_initial:
        type: csv
        file: "fragility_curve_initial.csv"
    fragility_curve_cache_1:
        type: csv
        file: "fragility_curve_cache_1.csv"
    fragility_curve_cache_2:
        type: csv
        file: "fragility_curve_cache_2.csv"
    fragility_curve_cache_3:
        type: csv
        file: "fragility_curve_cache_3.csv"
    fragility_curve_cache_4:
        type: csv
        file: "fragility_curve_cache_4.csv"
    resulting_fragility_curve:
        type: csv
        file: "hidden_resulting_fragility.csv""

```
## Code
```python
from toolbox_continu_inzicht import Config, DataAdapter
from toolbox_continu_inzicht.base.fragility_curve import FragilityCurve

config = Config(config_path="config.yaml")
config.lees_config()
data_adapter = DataAdapter(config=config)
fragility_curve = FragilityCurve(data_adapter)
fragility_curve.load("fragility_curve_initial")
fragility_curve.cached_fragility_curves = {
    0: "fragility_curve_cache_1",
    1: "fragility_curve_cache_2",
    2: "fragility_curve_cache_3",
    3: "fragility_curve_cache_4",
}
## voeg hier je keuze toe, bijv:
# if wind_dir < 100:
#   index = 1
# else:
#   index = 2
index = 1
fragility_curve.load_effect_from_data_adapter(index)
data_adapter.output("resulting_fragility_curve", fragility_curve.as_dataframe())
```
:::
