
---
title: "Aquo grootheden"
---

Bij het inladen van belastingen wordt rekening gehouden met de Aquo standaard.
Voor toolbox continu inzicht kan het soms lastig zijn omdat de termen binnen de Aquo standaard valt.
Binnen de toolbox wordt de volgende meta data gebruikt:

| voorkeurslabel     | omschrijving       | id                                                                              | grootheid   | groep     | label              | definitie                                                                                                                                                                                                                                      | label_en              | units                                  |
|:-------------------|:-------------------|:--------------------------------------------------------------------------------|:------------|:----------|:-------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------|:---------------------------------------|
| Waterdiepte        | Waterdiepte        | [4723.0](https://www.aquo.nl/index.php/Id-bd283cb5-2f2e-460a-9286-44252f136179) | WATDTE      | Grootheid | waterdiepte        | verticale afstand tussen waterspiegel en waterbodem                                                                                                                                                                                            | water depth           | m                                      |
| Waterhoogte        | Waterhoogte        | 4724.0                                                                          | WATHTE      | Grootheid |                    |                                                                                                                                                                                                                                                | water height          | m+NAP                                  |
| Windrichting       | Windrichting       | [4748.0](https://www.aquo.nl/index.php/Id-e955993f-b546-4603-ad85-5e84e77a1293) | WINDRTG     | Grootheid | windrichting       | de richting van waaruit de wind waait                                                                                                                                                                                                          | wind direction        | ° tov Noord waar de wind vandaan komt  |
| Windsnelheid       | Windsnelheid       | [4749.0](https://www.aquo.nl/index.php/Id-283501d0-7c17-4e9d-9543-c042698da112) | WINDSHD     | Grootheid | windsnelheid       | de gemiddelde snelheid van luchtdeeltjes in de (buiten) lucht                                                                                                                                                                                  | windspeed             | m/s                                    |
| Golfhoogte         | Golfhoogte         | [3640.0](https://www.aquo.nl/index.php/Id-fcfe2e65-3fde-401a-9f75-d9bbca883d2b) | GOLFHTE     | Grootheid | golfhoogte         | verticale afstand tussen golftop en golfdal                                                                                                                                                                                                    | wave height           | m                                      |
| Temperatuur        | Temperatuur        | [1522.0](https://www.aquo.nl/index.php/Id-368757fa-38b2-4b6a-910f-72e849810ba9) | T           | Grootheid | temperatuur        | maat voor hoe warm of koud iets is                                                                                                                                                                                                             | temperature           | ° Celcius                              |
| Temperatuur lucht  | Temperatuur lucht  | -1.0                                                                            | TLCHT       |           |                    |                                                                                                                                                                                                                                                | temperature air       | ° Celcius                              |
| Temperatuur water  | Temperatuur water  | -2.0                                                                            | TWAT        |           |                    |                                                                                                                                                                                                                                                | temperature water     | ° Celcius                              |
| Stroomrichting     | Stroomrichting     | [4513.0](https://www.aquo.nl/index.php/Id-d929235a-0943-4bcb-a3f3-1914c3c5e91d) | STROOMRTG   | Grootheid | stroomrichting     | richting waarin het water stroomt. De richting die een stroom volgt, d.w.z. de richting van de snelheid van een stromend medium.                                                                                                               | current direction     | ° tov Noord waar de stroming heen gaat |
| Stroomsnelheid     | Stroomsnelheid     | [4519.0](https://www.aquo.nl/index.php/Id-ce7672a9-b215-4f1c-ba6b-c048fbc26bd5) | STROOMSHD   | Grootheid | stroomsnelheid     | de gemiddelde stroomsnelheid van het water, zijnde het quotiënt van de cumulatieve aanvoerhoeveelheid en de natte oppervlakte                                                                                                                  | current speed         | m/s                                    |
| Debiet             | Debiet             | [3300.0](https://www.aquo.nl/index.php/Id-9b6c011f-f6df-4293-8b30-f12e528b9176) | Q           | Grootheid | debiet             | het volume van een vloeistof of een gas dat per tijdseenheid door een doorsnede stroomt                                                                                                                                                        | flow rate             | m3/s                                   |
| Saliniteit         | Saliniteit         | [4103.0](https://www.aquo.nl/index.php/Id-f0cb40fc-8834-4c5b-ab14-edaaa10c9f53) | SALNTT      | Grootheid | saliniteit         | het totale gewicht aan vaste stof per gewichtseenheid water, als alle carbonaatzouten zijn omgezet in oxiden, alle organische stof is geoxideerd en alle bromide- en jodide-ionen zijn vervangen door equivalente hoeveelheden chloride-ionen. | salinity              | g/kg                                   |
| Actuele verdamping | Actuele verdamping | [4628.0](https://www.aquo.nl/index.php/Id-d0fd56cb-3091-4eb5-8084-76917e37ab94) | VERDPG      | Grootheid | actuele verdamping | is de verdamping vanuit bodem en vegetatie                                                                                                                                                                                                     | precipitation         | mm                                     |
| Neerslag           | Neerslag           | [3991.0](https://www.aquo.nl/index.php/Id-8ab293ca-ca4d-4738-b38c-380e92263446) | NEERSG      | Grootheid | neerslag           | water in vaste of vloeibare vorm dat uit de atmosfeer op het aardoppervlak valt                                                                                                                                                                |                       | mm                                     |
| Neerslagoverschot  | Neerslagoverschot  | [5171.0](https://www.aquo.nl/index.php/Id-e8fc9b10-3657-4acb-a8d2-3681bac8e4d9) | NEERSOVST   | Grootheid | neerslagoverschot  | het verschil tussen de netto neerslag en de verdamping                                                                                                                                                                                         | precipitation excess  | mm                                     |
| Neerslagtekort     | Neerslagtekort     | [5824.0](https://www.aquo.nl/index.php/Id-035ab6b4-10e5-458d-afec-ac071a1595c8) | NEERSTKRT   | Grootheid | neerslagtekort     | het verschil tussen de verdamping en de netto neerslag                                                                                                                                                                                         | precipitation deficit | mm                                     |
| Actuele verdamping | Actuele verdamping | [4627.0](https://www.aquo.nl/index.php/Id-d0fd56cb-3091-4eb5-8084-76917e37ab94) | VERDPG      | Grootheid | actuele verdamping | is de verdamping vanuit bodem en vegetatie                                                                                                                                                                                                     | evaporation           | mm                                     |
| X-coordinaat       | X-coordinaat       | 4768.0                                                                          | X_CODNT     | Grootheid |                    |                                                                                                                                                                                                                                                | x-coordinaat          | -                                      |
| Y-coordinaat       | Y-coordinaat       | 4772.0                                                                          | Y_CODNT     | Grootheid |                    |                                                                                                                                                                                                                                                | y-coordinaat          | -                                      |
| Astronomisch getij | Astronomisch getij | -3.0                                                                            | GETIJ       |           |                    |                                                                                                                                                                                                                                                | astronomical tide     | cm tov MSL                             |
| Grondwaterstand    | Grondwaterstand    | -4.0                                                                            | WATGRD      |           |                    |                                                                                                                                                                                                                                                | groundwater level     | m+NAP                                  |

 _Dit is een automatisch gegenereerde tabel, zie de [bron code voor meer informatie](https://github.com/continu-inzicht/toolbox-continu-inzicht/tree/main/src/toolbox_continu_inzicht/base/aquo_meta_data)_
